parameters:
    pim_enrich.view_element.tab.channel_property.template:  'PimEnrichBundle:Channel:Tab/property.html.twig'
    pim_enrich.view_element.tab.channel_history.template:   'PimEnrichBundle:Form:Tab/history.html.twig'

services:
    pim_enrich.view_element.tab.channel_property:
        parent: pim_enrich.view_element.base
        arguments:
            - 'tab.pim_enrich_channel_edit.property'
            - %pim_enrich.view_element.tab.channel_property.template%
        tags:
            - { name: pim_enrich.view_element, type: pim_enrich_channel_form.form_tab, position: 90 }

    pim_enrich.view_element.tab.channel_history:
        parent: pim_enrich.view_element.base_protected
        arguments:
            - 'tab.pim_enrich_channel_edit.history'
            - %pim_enrich.view_element.tab.channel_history.template%
            - ['pim_enrich_channel_history']
        calls:
            - [ addVisibilityChecker, ['@pim_enrich.view_element.visibility_checker.edit_form'] ]
        tags:
            - { name: pim_enrich.view_element, type: pim_enrich_channel_form.form_tab, position: 110 }
