parameters:
    pim_enrich.view_element.tab.grouptype_property.template:  'PimEnrichBundle:GroupType:Tab/property.html.twig'

services:
    pim_enrich.view_element.tab.grouptype_property:
        parent: pim_enrich.view_element.tab.base
        arguments:
            - %pim_enrich.view_element.tab.grouptype_property.template%
            - 'tab.pim_enrich_grouptype_edit.property'
        tags:
            - { name: pim_enrich_view_element.tab, position: 90, identifier: pim_enrich_grouptype_edit}
