parameters:
    pim_enrich.view.tab.product_comment.template: 'PimCommentBundle:Product:Tab/comment.html.twig'
services:
    pim_enrich.view.tab.product_comment_base:
        parent: pim_enrich.view.tab.base
        arguments:
            - %pim_enrich.view.tab.product_comment.template%
            - 'tab.pim_enrich_product_edit.comment'

    pim_enrich.view.tab.product_comment:
        parent: pim_enrich.view.tab.granted
        arguments:
            - @pim_enrich.view.tab.product_comment_base
            - 'pim_enrich_product_comment'
        tags:
            - { name: pim_enrich_views.tab, position: 125, identifier: pim_enrich_product_edit}
